name: Update

on:
  schedule:
    # 每天 UTC 时间 05:10 运行（北京时间 13:10）
    - cron: '10 5 * * 1-5'
  workflow_dispatch:      # 添加手动触发功能

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Generate content
      run: |
        pip install -r requirements.txt  # 如果有依赖需要安装
        python main.py --base_url ${{ secrets.BASE_URL }} --model ${{ secrets.MODEL }} --api_key ${{ secrets.API_KEY }}

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add README.md
        git commit -m "Auto-update content" || echo "No changes to commit"
        git push
